default_platform(:ios)

platform :ios do
  desc 'Push a new beta build to TestFlight'
  lane :beta do
    # __dir__ is the absolute path to the fastlane/ directory containing this Fastfile
    key_path = File.expand_path("keys/AuthKey_98UDF59KU7.p8", __dir__)

    app_store_connect_api_key(
      key_id: "98UDF59KU7",
      issuer_id: "32df2f83-b463-468f-95aa-f43b10192828",
      key_filepath: key_path,
      duration: 1200,
      in_house: false
    )

    build_app(
      workspace: 'Runner.xcworkspace',
      scheme: 'Runner',
      export_method: 'app-store',
      xcargs: "-allowProvisioningUpdates -authenticationKeyPath '#{key_path}' -authenticationKeyID 98UDF59KU7 -authenticationKeyIssuerID 32df2f83-b463-468f-95aa-f43b10192828 ENABLE_BITCODE=NO"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc 'Push a new release to App Store'
  lane :release do
    key_path = File.expand_path("keys/AuthKey_98UDF59KU7.p8", __dir__)

    app_store_connect_api_key(
      key_id: "98UDF59KU7",
      issuer_id: "32df2f83-b463-468f-95aa-f43b10192828",
      key_filepath: key_path,
      duration: 1200,
      in_house: false
    )

    build_app(
      workspace: 'Runner.xcworkspace',
      scheme: 'Runner',
      export_method: 'app-store',
      xcargs: "-allowProvisioningUpdates -authenticationKeyPath '#{key_path}' -authenticationKeyID 98UDF59KU7 -authenticationKeyIssuerID 32df2f83-b463-468f-95aa-f43b10192828 ENABLE_BITCODE=NO"
    )
    upload_to_app_store(
      force: true,
      submit_for_review: false
    )
  end
end
